# learning rate
LR: 0.001

EPOCHS: 200
DEVICE: cuda
N_WORKERS: 4
BATCH_SIZE: 32
SEED: 303

# dataset path
DS_PATHS:
  widerface: /nas/softechict-nas-3/rgasparini/datasets/widerface
  face_mask: /nas/softechict-nas-3/rgasparini/datasets/face_mask_dataset

DS_CLASSIFY: 0

# network input shape as keras channel last ordering separated by ',' , data input will be resized to that shape proportionally and keeping the original AR
INPUT_SHAPE: 352,352,3

SRTIDE: 4

MODEL: resnet

# convert to tflite [True, False]
EXPORT_TFLITE: True
