# learning rate
LR: 0.0001

EPOCHS: 10
DEVICE: cuda
N_WORKERS: 4
BATCH_SIZE: 256

# dataset path
DS_PATH: '/home/rgasparini/Documents/cat_dog'

# network input shape as keras channel last ordering separated by ',' , data input will be resized to that shape proportionally and keeping the original AR
INPUT_SHAPE: 128,128,3
